### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by hybtoy**

### CODE REVIEW

**Comment by crapthings** [comment]
awesome twist

**Comment by m4niacjp** [comment]
There is actually a problem while setup the APACHE Server.

As per obfs instruction it should be setup on a different port than 80/443 as these will still be used by obfs-server. 
If you try to start the apache2.service it clearly mentions that port 80/443 is already occupied (true) and service can't start.

**Comment by hybtoy** [comment]
@m4niacjp 
So what is the solution?

**Comment by Unbinilium** [comment]
All the typos will be rewrite later, fix it that time.

**Pull request closed without merging**
