### PR TITLE
create twistbackup path if not exist

### PR DESCRIPTION
**Pull request by zhangciwu**
When using, it reports:
cp: cannot create regular file '/etc/twistbackup/sysctl.conf': No such file or directory

So I fix it.

### CODE REVIEW

**Comment by Unbinilium** [comment]
Thanks for your feedback! But i think it is not a bug if you are using twist that recently updated. It may caused by the old version because the backup place was changed in newer version. For
 `mbedtls using 2.6.0 cause 2.7.0 will cause error when compile`, i added  `mbedver=""` in `function systemconfig(){`. I can not reproduce any error in mbedtls 2.7.0 that you've mentioned. So i added some code to change version eaisliy. I anyone meet it, try that first.

**Comment by zhangciwu** [comment]
Take a close look, the code I wrote is wrong, but

In tcpbbrenable():
line 427 cp to /etc/twistbackup/

In sslibevconfigure():
line 540 create /etc/twistbackup/

But tcpbbrenable is invoked before sslibevconfigure
I think this is why I met this error.(I use the github master version yesterday)

In tcpbbrenable check twistbackup exists or create it should solve this.

**Comment by zhangciwu** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1935

I met the same problem:

> ss_local-crypto.o: In function mbedtls_md5': /usr/local/include/mbedtls/md5.h:316: undefined reference tombedtls_md5_ret'

I switch to 2.6.0 then solve it like that issue said.
Not very clear why, post this for reference.

**Comment by hybtoy** [comment]
@Unbinilium 
twist.sh: line 409: syntax error near unexpected token `elif'
twist.sh: line 409: `    elif [ "$packagemanagertype" = "y" ]; then'
On CentOS 7

**Comment by Unbinilium** [comment]
Thanks a lot! I’m trying to solve these problems!

**Comment by Unbinilium** [comment]
@zhangciwu Thanks! fixed

**Comment by Unbinilium** [comment]
@hybtoy Thanks! fixed

**Pull request closed without merging**
